name: Cache Example

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cache-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Python dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-1a736b4

      - name: prime-cache-1a736b4
        run: |
          echo "Cache hit: ${{ steps.cache-step.outputs.cache-hit }}"
          if [[ "${{ steps.cache-step.outputs.cache-hit }}" == 'true' ]]; then
            echo "Dependencies restored from cache."
          else
            echo "Cache miss. Dependencies will be installed and cached."
          fi
